server:
  port: 8080

spring:
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
  sql:
    init.mode: always
  data:
    redis:
      host: localhost
      port: 6379

  # jpa properties
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: true
  servlet:
    multipart:
      maxFileSize: 100MB
      maxRequestSize: 100MB

app:
  jwt-secret: hisooandyoungwooletsplaywithdivinityclashwewillberich
  jwt-expiration-milliseconds: 3600000 # 1시간(3600초 * 1000)